//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClasTech.Teste.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoItem
    {
        public int id { get; set; }
        public int produtoId { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public bool ativo { get; set; }
    }
}
